### ISSUE TITLE
Requires external exe

### ISSUE THREAD

**Issue by berserker001** [markmal/freeship-plus-in-lazarus#102]
Dear markmal, can you please tell me where I can download the exe's in the Exec directory such as ADD_MASS.EXE, Pos_Ship.EXE, Rot_Ship.EXE, Ishercof.EXE, propol.exe, HOLLENBH.EXE, OORTMERS.EXE, fungleb.EXE, hship.EXE, ManeuvPP.EXE, CALCPROP.EXE, PropPred.EXE, RVRSSHIP.EXE?

**Comment by markmal** [comment]
Hi Berserker,
all exes are packaged. You should find then in the <applications>/Freeship/Exec folder
