### ISSUE TITLE
5.0.36.475 agressively offering updates preventing use of application

### ISSUE THREAD

**Issue by Samarang** [markmal/freeship-plus-in-lazarus#105]
Is there a way of preventing update checking? The updater is going off constantly and preventing work in version 5.0.36.475. Updating is a no-go as MX 21 does not support  glibc_2.34. Thanks!

**Comment by markmal** [comment]
Hi @Samarang 
what is MX 21?
the app works in mine Ubuntu 22.04.4 LTS

**Comment by Samarang** [comment]
Hi!
MX Linux 21, based on Debian 11. I have been using firejail to prevent it accessing the net, which prevents the update dialogue from appearing. I was hoping there was a switch to turn off net access. The updater notification appears just about every time you select an edge or control point and takes to clicks to cancel out of (it respawns after the first click), so it's pretty annoying. 
Thanks for reading!

**Comment by markmal** [comment]
both Deb 11 and Ubuntu 22.04.4 have same package libstdc++2.9-glibc2.1-dev. And the app works on Ubuntu 22.04.4.
"The updater notification appears just about every time you select an edge or control point" - this sounds weird. As I remember the Update checker kicks in on startup.
Anyway I'll check.

**Comment by markmal** [comment]
I've found the issue with "updater notification appears just about every time".
Fixed. Included into next release.

**Comment by Samarang** [comment]
Thanks heaps! Great to know the project is still active :)
