### ISSUE TITLE
Links in the readme to Hydronship.net show site there not working

### ISSUE THREAD

**Issue by l-arnold** [markmal/freeship-plus-in-lazarus#107]
**The domain hydronship.net is for sale. To purchase, call BuyDomains.com at ....**

Might be better to link back to 
https://sourceforge.net/projects/freeship/

but it does seem that Hydronship had a Plus version in the middle of yours and the sourceforge project.

https://freeship-plus.en.softonic.com/

**Comment by markmal** [comment]
Hi @l-arnold 
yes some links do not work. 
I'll change to https://sourceforge.net/projects/freeship/

**Comment by markmal** [comment]
fixed
