### ISSUE TITLE
problem with layers name

### ISSUE THREAD

**Issue by SergeyShorin** [markmal/freeship-plus-in-lazarus#11]
I'm load file after editing it Windows version. If layers name in that file contains not-english characters - they displayed as "???????". I can rename layer use russian characters, save and load file - all ok, displayed like I typed (mix english and russian characters). tomorrow I check this file at my office computer (Win XP), and say what happened with layers names.

p.s. I try add project file, but can't. so I rename -001.fbm to -001.fbm.png - so You can see: first and second layers named in mix-language characters:
"first-первый" and "second-второй"
![-001 fbm](https://cloud.githubusercontent.com/assets/10895820/10171442/9660b0c6-66f3-11e5-84a6-6703f7d9f914.png)

**Comment by markmal** [comment]
FreeShip for Lazarus stores texts in Unicode (UTF8). I suspect that Windows version stores in Windows Russian codepage 1251 (8-bit character encoding).
Problem with 8-bit character encodings it is impossible to say in what language national characters (with codes >128) were typed. Code 192 means A in Russian 1251, and something else in Arabic 1255 etc. There is no such problem with UTF8.

I will check if codepage or/and language is specified in .FBM format. If yes, it will be possible to translate from UTF8 to a Windows codepage. If not, we can only rely on Language that set in FreeShip. User have to set same in Windows and in Lazarus/Linux one.

Also, please keep in mind, despite Lazarus version was started as clone from Windows one, it is getting more and more different, for following reasons: different OS, different programming environment, and improvements and bug-fixes are going independently now. Simply speaking, it is not guaranteed, that FBM files created in one program are 100% compatible with another one. Though I am trying my best.

**Comment by SergeyShorin** [comment]
O! sure! I'm understanding that different between win and lin (I'm programming in window visual basic and in linux gambas)
ok.
let's see what we have in project with renaming layers in linux:
first and second layer have @#%&&^%#$% name, other have normal readable russian name.
![layername_from_linux_to_windows](https://cloud.githubusercontent.com/assets/10895820/10183585/1fe81c30-6753-11e5-9810-3159e5a8cdd6.JPG)


I'm not sure what *.fbm format have "character-set option" and may consist UTF-8 characters.
and not sure what this problem can be resolved - but You see better :-) (may be You communicate with windows-developer of FreeShip)

**Comment by markmal** [comment]
It is in FreeShip for Windows, correct?
What shows FreeShip for Linux? Please post similar picture.

**Comment by markmal** [comment]
Sergey, please note that you have to set correct encoding in Preferences. For Russian it should be cp1251. In Windows you also should use 1251.
Please test and let me know.

**Comment by SergeyShorin** [comment]
yes, in windows locale cp1251, but in linux I use utf8 (
![locale](https://cloud.githubusercontent.com/assets/10895820/10282431/54e14e80-6b94-11e5-801d-324698270ac4.png)
)
same file in linux (
![screenshot2](https://cloud.githubusercontent.com/assets/10895820/10282438/5dca71fc-6b94-11e5-9e2a-d65b02103ee0.png)
)

p.s. on locale.png You can see semi-transparent terminal window :-)

**Comment by markmal** [comment]
in Linux FreeShip 3.5.3.29 open File/Preferences and set FBM Encoding to cp1251. 
Then save your model as .fbm file. Then open it in Windows FreeShip.

**Comment by SergeyShorin** [comment]
ok. I'll try this today at home.

**Comment by markmal** [comment]
Hi Sergey, 
did not hear from you.
My tests work well. 
I am closing this issue.
