### ISSUE TITLE
100% CPU in Linesplan window mode

### ISSUE THREAD

**Issue by cipman** [markmal/freeship-plus-in-lazarus#13]
How to reproduce:
   - open FreeShip > New (or keep/open an existing project)
   - menu > Project > Linesplan => the new linesplan window pops up => 100%CPU and you can see the cursor rapidly switching from cross to wait mode
- close the linesplan window and all back to normal.

**Comment by markmal** [comment]
Please note that font size adjustment control is added for main and Linesplan window.
Original automatic font size selection caused repaint race and 100% CPU.
Now font size is 8 by default, you can adjust it to any size from 3 to 20.
Please test build 29 and let me know.

**Comment by cipman** [comment]
Build 29 works fine. Thanks.

**Comment by markmal** [comment]
Thank you!
closed
