### ISSUE TITLE
Design Hydrostatics not working

### ISSUE THREAD

**Issue by cipman** [markmal/freeship-plus-in-lazarus#14]
How to reproduce:
- start FreeShip
- menu > File > New [accept defaults] > Ok (or keep existing project)
- menu > Calculations> Design Hydrostatics 
A window pops up saying:
<<<Unable to create file "FreeHydrostaticsMode.ShowData.Strings.txt".
Press OK to ignore and risk data corruption.
Press Cancel to kill the program.>>>

It woks fine if FreeShip is started from a terminal in a folder where the user has write permission, so I believe  it's something like issue https://github.com/markmal/freeship-plus-in-lazarus/issues/6

**Comment by cipman** [comment]
Works fine with the new 29 build.

**Comment by markmal** [comment]
Thank you!
closed
