### ISSUE TITLE
.deb install gives non-valid

### ISSUE THREAD

**Issue by tvld** [markmal/freeship-plus-in-lazarus#18]
![not_valid](https://cloud.githubusercontent.com/assets/986182/11913717/08461df2-a66e-11e5-9f73-b3cfad36d60f.png)

**Comment by markmal** [comment]
Thanks, I'll check.
Interesting, I've checked the .deb with lintian, it did not show this issue.

**Comment by tvld** [comment]
I downloaded again and same issue. ( Ubuntu 14.04 LTS, Core i7 )

**Comment by markmal** [comment]
Ubuntu Software Center demands Installed-Size field that is not mandatory in Debian Policy.
I've added this field. 
Also made some other small fixes.
Check version 3.5.5.12 in https://github.com/markmal/freeship-plus-in-lazarus/releases/

**Comment by tvld** [comment]
Installs ok now :) ...  But now I get 
```
~$ freeship
freeship: command not found
```

**Comment by tvld** [comment]
I see first time the logo's  I made last summer... But they have anti-alias problem which does not make me proud... will have a look ;)

**Comment by tvld** [comment]
![language](https://cloud.githubusercontent.com/assets/986182/11915461/9b7b0dba-a6a7-11e5-9383-90b4e948abb7.png)

**Comment by markmal** [comment]
.pxm Logo I've converted from 32/00-freeship.png with quite simple convert command

Also I've added size 96. (just to fill gap in sequence 16 24 32 48 64 96 128)

It looks like program overrides config at $HOME/FreeShip/FreeShip.ini . I'll check.

**Comment by markmal** [comment]
Probably, you have not run uninstall-user.sh. Or it was too old. 
New version does not have these artefacts.
Anyway, you can fix it manually in application File/Preferences ->Directories. 
Or you can delete .config/FreeShip/FreeShip.ini or or edit it with removing all lines from [Directories] section.

**Comment by tvld** [comment]
I did indeed not uninstall anything. I just hit "upgrade" when opening the .deb with Ubuntu's Software centre. 
Selecting `/usr/share/FreeShip/Languages` worked. Thanks )

**Comment by tvld** [comment]
We are mixing issues here. About the icons:  `make_freeship_menu_icon_sprite.sh` should work with 96dpi icons as well. Maybe there is a wrong background color chosen to be able to anit-alias properly given that pixels can not be semi-transp in icons....

**Comment by markmal** [comment]
background color? I thought icons are in RGBA format (with Alpha channel). Aren't they?

**Comment by markmal** [comment]
If there are problems with icons, can we create separate issue? 
I would close this issue as soon as .deb works well and major package managers do not complain.

**Comment by tvld** [comment]
Yes. Good to close it. I will play a bit more and come back to it if needed ))

On 21 December 2015 16:46:56 CET, Mark Malakanov <notifications@github.com> wrote:
>If there are problems with icons, can we create separate issue? 
>I would close this issue as soon as .deb works well and major package
>managers do not complain.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/markmal/freeship-plus-in-lazarus/issues/18#issuecomment-166335299

-- 
Sent from my mobile.

**Comment by markmal** [comment]
closing! :)
