### ISSUE TITLE
Make 32bit build for Linux

### ISSUE THREAD

**Issue by Symbian9** [markmal/freeship-plus-in-lazarus#21]
Please, make 32bit deb binary for linux too! 
(for Trusty 14.04)

**Comment by markmal** [comment]
Hi, I tried. There are some issues with cross compiling of fpc for i386. For now I am not sure how to resolve them.

Just wondering, what nowadays makes you staying on i386, not amd64?

**Comment by Symbian9** [comment]
@markmal,
I have laptop that support both working mod: x86 & x86_64
<b>But, in x86 mod all applications run faster!</b>

PC: 
* Samsung R58+

Installed OS:
* x86 - PuppyLinux Tahr (14.04)
* x86_64 -LinuxMint 16
