### ISSUE TITLE
Строевая по шпангоутам

### ISSUE THREAD

**Issue by vla2849** [markmal/freeship-plus-in-lazarus#22]
Марк привет!

Что-то не заходишь на форум FS-па. Я обновился до последней версии Debian 8.5. Не отрисовывается строевая по шпангоутам и не отображаются характерные точки - ЦВ, ЦТ и т.д.

С уважением,
Владимир.

**Comment by markmal** [comment]
Привет Владимир!
Все лето отдыхал, занимался практическим судостроением (делал и ремонтировал гидрофойл для виндсерфинга, учился кататься)
Скоро посмотрю в чем проблема.

**Comment by vla2849** [comment]
Добрый день Марк! У меня подозрение на то, что в восьмом дебиане по умолчанию система инициализации systemd, может где-то что-то не докрутили. И вообще с этой системой инициализации стало не возможно нормально выключить ноутбук, т.е. из меню (у меня LXDE). В предыдущей 7-й всё работало отлично. Пытаюсь разобраться, но так как с английским напряг, то приходится искать на русском. А с подводным крылом к соревнованиям допускают? Интересно, при какой скорости ветра виндсёрфинг выходит на крыло? А если наедешь на подводное препятствие - крыло на отвалится? -- С уважением,               Владимир Ветров.   31.10.2016, 15:58, "Mark Malakanov" <notifications@github.com>:Привет Владимир!Все лето отдыхал, занимался практическим судостроением (делал и ремонтировал гидрофойл для виндсерфинга, учился кататься)Скоро посмотрю в чем проблема.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by vla2849** [comment]
Марк привет!
Поздравляю с наступающим Новым 2017 годом! Желаю успехов как в работе, так и в жизни и самого главного - богатырского здоровья для занятий парусным спортом, ну и вообще быть здоровым всегда и везде.

Ну а теперь немного о грустном. Я специально поставил FS под WIN 7. чтобы посмотреть будет ли отрисовываться строевая по шпангоутам и характерные точки - увы этого не случилось. 
![error-fs-3 6-01](https://cloud.githubusercontent.com/assets/20470662/21576149/c3eb2d8c-cf3e-11e6-9147-c45800397f62.jpg)

Ещё при выходе из программы появилось сообщение
![error-fs-3 6-02](https://cloud.githubusercontent.com/assets/20470662/21576154/d0214726-cf3e-11e6-898f-04378816e5be.jpg)
Жмёшь "OK" - из программы не выходит, "Cancel" - выходит. Как говорится - "вот такие новогдние пироги".

**Comment by markmal** [comment]
Issue with slashes / \ is fixed.
