### ISSUE TITLE
http://hydronship.net EXPIRED???

### ISSUE THREAD

**Issue by Symbian9** [markmal/freeship-plus-in-lazarus#23]
Where official site now?
- http://www.hydronship.net/

Currently it give this

> This domain name expired on Oct 15 2016 06:33:22:000AM
- Snapshot - http://archive.is/crHu7

### MIRROR?
- http://freeship-plus.ho.ua/

**Comment by markmal** [comment]
Hi!
FreeShip Plus in Lazarus is independent fork of FreeShip Plus from Hydronship. 
I do not know of destiny of the former one and do not control it.
hydronship.net is not official site of FreeShip Plus in Lazarus. It looks like some generic domain name search site. 
It is sad to know that Hydronship is not supported any more. At least as it looks like.

FreeShip Plus in Lazarus is advanced with fixing multiple bugs, as well as some improvements have been implemented.
It was started with thought to be able to work in Linux.
However the latest version is compiled for Windows too.

**Comment by Symbian9** [comment]
But here is actual official mirror for original FREE!Ship Plus by Timoschenko V.F.
* http://freeship-plus.ho.ua/

So, I recommend you use this mirror link!

**Comment by Symbian9** [comment]
http://freeship-plus.ho.ua/ now return Error 403...

WTF?

**Comment by gardner** [comment]
I just called the domain squatters. They want $4,888.00USD for the domain.
