### ISSUE TITLE
FREE!ship + Lazarus 1.6 backport on Trusty 14.04LTS

### ISSUE THREAD

**Issue by Symbian9** [markmal/freeship-plus-in-lazarus#24]
https://launchpad.net/~ok2cqr/+archive/ubuntu/playground/+packages

**Comment by markmal** [comment]
Hello,
I am not sure I understand what is the issue?

**Comment by Symbian9** [comment]
Need instruction on how install FREE!Ship under 14.04LTS.

**Comment by markmal** [comment]
Are there any issues when you try to install freeship_3.6.0.16-all_amd64.deb ?
It can be downloaded from here https://github.com/markmal/freeship-plus-in-lazarus/releases
