### ISSUE TITLE
dll error

### ISSUE THREAD

**Issue by helicomarcelo** [markmal/freeship-plus-in-lazarus#26]
After installation it appears the missing dll information "libstdc ++ = 6.dll" and libgcc_s_dw2-1.dll "

**Comment by markmal** [comment]
Hi,

I have not tested the program with Win 10.

**Comment by helicomarcelo** [comment]
Do you know if it is installer or windows error.

**Comment by markmal** [comment]
It is Windows and application compatibility error.
The application depends on DLL that is absent in Windows.

**Comment by helicomarcelo** [comment]
I have managed to solve the problem with the dll, but now the error is (0xc000007b).
You know of someone who has managed to install on windows.

**Comment by markmal** [comment]
I've installed and tested on Win 7

I'll check if I could find Win 8 and 10

Please send full error message

**Comment by helicomarcelo** [comment]
The message that appears is " The application was unable to start correctly (0xc000007b). Click Ok to close the application".
This happens in win 7 e win 10.

**Comment by vla2849** [comment]
Марк привет!
Вот такая ошибка в ОС WIN7. Где же взять эту dll-ку?
![error-fs-3 6](https://cloud.githubusercontent.com/assets/20470662/21536934/037b4844-cda3-11e6-8738-d7bbbea2b0d8.jpg)

**Comment by markmal** [comment]
It should be in QT4 Runtime. Should be installed separately.
What QT4 is installed on your Win7?

Эта DLL должна быть в QT4 рантайме. Его надо установить отдельно.
Какой QT4 установлен на Win7?

**Comment by vla2849** [comment]
У меня под Win вообще не установлена QT4 рантайм. Может необходимые DLL-ки в составе релиза загружать? Пошарил по сайту QT нашёл только это -http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-vs2010-4.8.7.exe и http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-mingw482-4.8.7.exe. Что же из них устанавливать?

**Comment by vla2849** [comment]
Ещё нашёл утилиту Dependency, которая показывает чего же не хватает программе для выполнения в среде ОС. На перво скрине чего не хватает. На втором скрине разные архитектуры CPU.
![dependency-01](https://cloud.githubusercontent.com/assets/20470662/21559653/a4508a88-ce69-11e6-808e-d52695566970.jpg)
![dependency-02](https://cloud.githubusercontent.com/assets/20470662/21559684/3d871c6c-ce6a-11e6-912d-e3bb4923bc58.jpg)

**Comment by markmal** [comment]
Please install 
http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-vs2010-4.8.7.exe
I cannot include Qt DLLs into FreeShip package. Qt4 runtime needs to be 
installed.

Я не могу включить Qt ДЛЛ-ки во FreeShip. Необходимо установить Qt4 runtime.

**Comment by markmal** [comment]
I've read Qt instructions again. I seems that it allows including just 
required Qt DLLs into package for redistribution.
Please postpone with installation of full Qt4 opensource.

I will find all required DLLs and include them into FreeShip.


Я прочитал Qt инструкции, кажется Qt позволяет включать только 
необходимые ДЛЛки в свой пакет для редистрибуциии.
Пока не ставьте Qt4 opensource.
Я найду все требуемые ДЛЛ-ки и включу в пакет FreeShip.

**Comment by markmal** [comment]
All required Qt4 DDLs are included.
You do **not** have to install Qt4-opensource.

Все необходимые ДЛЛ-ки включены в пакет.
Вам **не** надо ставить Qt4-opensource

**Comment by markmal** [comment]
Starting from release 4.1.1 FreeShip does not depend on QT. 
FreeShip works in Win10
