### ISSUE TITLE
can't run executable

### ISSUE THREAD

**Issue by SergeyShorin** [markmal/freeship-plus-in-lazarus#27]
Hello! 
I try run FS on Linux Mint 18.1 "Serena" with Xfse 32-bit.
install in both mode (user and system).
but if I click item in menu - nothing happening, and if I run from terminal - error:
cannot execute binary file: Ошибка формата выполняемого файла
translate russian to english (word-word):
cannot execute binary file: error format executable file.
can You check this problem?
![can_not_run_fs](https://cloud.githubusercontent.com/assets/10895820/23865138/e0f51d50-083e-11e7-909a-4a9f899d00e8.png)

**Comment by markmal** [comment]
Hi Sergey,

try on 64-bit platform.

**Comment by SergeyShorin** [comment]
Ok. I'm understand... but I have not 64-bit platform.
