### ISSUE TITLE
Failure to compile due to hard coded path in FreePackage

### ISSUE THREAD

**Issue by gardner** [markmal/freeship-plus-in-lazarus#28]
This is an import from https://sourceforge.net/p/freeship-plus-in-lazarus/tickets/3/

When trying to compile FreeShip for the first time with Lazarus/FPC on Linux, it doesn't work out-of the box.
First, FreePackage package is needed, but in freeship-plus-in-lazarus-code/Packages/FreePackage.lpk there are directory names like home/mark left.

**Comment by markmal** [comment]
Hi, I trying to strip of FeeShip component and will use it directly as a regular classes. This will eliminate the need of installing it in Lazarus IDE and all related local path issues.

**Comment by markmal** [comment]
Starting from release 4.1.1 there is no dependency on custom packages.
