### ISSUE TITLE
qt4 libs are deprecated

### ISSUE THREAD

**Issue by nkh** [markmal/freeship-plus-in-lazarus#34]
any way to get this too install on a new distro?

sudo dpkg -i freeship_3.6.0.16-all_amd64.deb
[sudo] password for nadim:
Selecting previously unselected package freeship.
(Reading database ... 288628 files and directories currently installed.)
Preparing to unpack freeship_3.6.0.16-all_amd64.deb ...
Unpacking freeship (3.6.0.16) ...
dpkg: dependency problems prevent configuration of freeship:
 freeship depends on libqt4pas | libqt4pas5 | libqt4pas-dev; however:
  Package libqt4pas is not installed.
  Package libqt4pas5 is not installed.
  Package libqt4pas-dev is not installed.

dpkg: error processing package freeship (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.4-2) ...
Processing triggers for desktop-file-utils (0.23-3ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 freeship
308 ~/1/downloads i libqt4pas libqt4pas5 libqt4pas-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libqt4pas is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libqt4pas5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libqt4pas-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libqt4pas' has no installation candidate
E: Package 'libqt4pas5' has no installation candidate
E: Package 'libqt4pas-dev' has no installation candidate

**Comment by markmal** [comment]
Hi just recently Lazarus 2.0.0 has been issued. I will try to migrate on Qt5.
For time being as far as I know it is possible to have multiple Qt versions on same machine.
