### ISSUE TITLE
Encoding or interface problems

### ISSUE THREAD

**Issue by mrkaban** [markmal/freeship-plus-in-lazarus#35]
Hello, apparently this problem has already been raised in ticket 25 ([link](https://github.com/markmal/freeship-plus-in-lazarus/issues/25)), but the person did not describe the problem to the end and did not begin to deal with the problem.

When running on Windows 10 x64 and Windows 7 x64, the text in the dialog boxes is incorrect, and the icons are incorrectly displayed.

The installation script ran. The program and the script run on behalf of the administrator.

**Comment by mrkaban** [comment]
![Снимок](https://user-images.githubusercontent.com/14289360/55867611-07369c00-5bad-11e9-89ed-70d75d9b993e.jpg)
![Снимок2](https://user-images.githubusercontent.com/14289360/55867612-07369c00-5bad-11e9-8097-70b12d286a97.jpg)
I attach screenshots, when I run the program, an error is displayed, it is also on the screenshot.

**Comment by markmal** [comment]
Fixed in 4.1.1.159

**Comment by mrkaban** [comment]
Forced again to raise the topic, since on Windows 10 x64 the same problem. version 4.1.1.159.

On Windows 7, I did not notice such a problem, so we can conclude that it was solved on this version of the OS.

![Снимок](https://user-images.githubusercontent.com/14289360/58268538-ccc93d00-7daf-11e9-801b-cf9e6a49c70a.jpg)
![Снимок2](https://user-images.githubusercontent.com/14289360/58268539-cd61d380-7daf-11e9-8c7b-cf1e7f2a0ad8.jpg)
