### ISSUE TITLE
open file crash linux

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#39]
Hi the latest build on my os (xubuntu 18.4) crash when I try to open a file.
![open_crash](https://user-images.githubusercontent.com/11751383/58752763-cecc8380-84b4-11e9-932c-8e3b819b6839.png)

**Comment by markmal** [comment]
Hi, I see the project is open. It crashes after that. 
Try to run FreeShip from bash terminal, what output do you see after crash?
If you could share (or email) the file it would be much simpler for me to trace.

**Comment by pafurijaz** [comment]
works well if I execute from terminal with FreeShip %f and I get this messages:

 (FreeShip:8287): GLib-GIO-CRITICAL **: 20:02:11.414: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
WARNING: TResourceCacheItem.IncreaseRefCount 1000 TFontHandleCache

**Comment by markmal** [comment]
I was able to reproduce a bug. Not sure if same. 
I created new hull with 60x50 points. Started program without --nosplash parameter. During loading I clicke to splash window to close it. After that I got the error.
There is code that tries to access objects of splash after it destroyed. I will fix it and let you know.
Workaround: run with --nosplash
./FreeShip --nosplash
PS/ using --nosplash you still agree with legal conditions of program usage. "No warranty of any kind...etc...etc..."

**Comment by pafurijaz** [comment]
Thanks for the tips, and for the developing. Mine Friend has this issue me too with wine. "It opens and seems to work in Windows 10, but all buttons across the top are just black boxes."

**Comment by markmal** [comment]
for Windows please follow install-HOWTO.txt

**Comment by pafurijaz** [comment]
Thanks man!
