### ISSUE TITLE
Open file

### ISSUE THREAD

**Issue by ddjokic** [markmal/freeship-plus-in-lazarus#40]
On Windows machines (7&10), can not open a file in 4+ branch of FreShip Lazarus. Open window appears, I can choose a file, even see a preview, but nothing appears in view windows.

**Comment by markmal** [comment]
It is performance issue for this test build. 
If project is complex or precision is high it may take couple of minutes to load such project. Try to decrease precision if it is not required for your editing task. Later you can increase it after editing.
After testing and fixing most of bugs I will disable debug and compiler check-ups. That should improve performance.
