### ISSUE TITLE
Impossible load some old files.

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#41]
Hi in the testing I had a problem to load some oldest files here some heavy hulls made by me..

[boat_hull.zip](https://github.com/markmal/freeship-plus-in-lazarus/files/3267117/boat_hull.zip)

**Comment by markmal** [comment]
I was able to load all files. Some of them, like yacht, it took >10min to open. Just be patient.

**Comment by pafurijaz** [comment]
Ok but with the old version they are loaded very fast.. and the version of FreeShip under wine on linux load fastest.

**Comment by markmal** [comment]
May be. I've turned on all checks in compiler. For types, arrays etc. Of course it slows everything down. When the program will be more or less stable I will turn off the checks.

**Comment by pafurijaz** [comment]
OK thanks I will wait for the next releases for now thanks. And now you have a very heavy file to test :)
