### ISSUE TITLE
Extrude edge does not accept negative values (win10)

### ISSUE THREAD

**Issue by patrik111** [markmal/freeship-plus-in-lazarus#42]
On version 4,2,2,175

I cannot get extrude command to accept negative values.

![2019-06-17-19-13-52](https://user-images.githubusercontent.com/32139980/59623860-9c1dbe80-9135-11e9-9c81-4bb2380191e2.gif)

**Comment by markmal** [comment]
Fixed. Will release soon.
Thanks for video!

**Comment by markmal** [comment]
4.3.2 released

**Comment by patrik111** [comment]
Works fine :)
