### ISSUE TITLE
No float value accepted 

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#44]
Hi first of thanks for your work, I discovered an other bug, in the editing panel when I set a value floating with paste or manual input in the length field, Freeship crash.

![freeship_input](https://user-images.githubusercontent.com/11751383/60624341-5293cb80-9de5-11e9-97d5-d40316ac534f.png)

FreeShip %f
FreeShip in Lazarus
Compiled at 2019/07/01 18:13:08
Compiler version: 3.0.4
Target CPU: x86_64
Target OS: Linux
FreeShip Product version: 4.3.2.0
FreeShip Program version: 4.3.2.191
Last Git Change Revision: 230

(FreeShip:29486): GLib-GIO-CRITICAL **: 22:42:12.513: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Program exception! 
Stacktrace:

Exception class: EConvertError
Message: "18,78" is an invalid float
  $00000000004A47FA
  $00000000004A47B7
  $00000000004ECF6C
  $00000000004635D6
  $0000000000804730
  $000000000045D23C
  $0000000000803F11
  $0000000000432D0F
  $000000000045A18D
  $0000000000803FBB
  $000000000088F542
  $0000000000864C65
  $0000000000872169
  $00000000007A7B79
  $00007F1C7E79B38B
WARNING: TFloatSpinEdit.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?
WARNING: TMenuItem.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?
[TGtk2WidgetSet.Destroy] WARNING: There are 24 unreleased GDIObjects, a detailed dump follows:
[TGtk2WidgetSet.Destroy]   GDIOs: 00007F1C6E45F5C0 00007F1C6E45F140 00007F1C6E45E240 00007F1C6E45D9C0 00007F1C6E45DA40 00007F1C6E45D7C0 00007F1C6E45F7C0
[TGtk2WidgetSet.Destroy]   gdiBitmap: 24

**Comment by markmal** [comment]
Fixed. Will release soon
