### ISSUE TITLE
Michlet file generator, Y1 wave value and Viscous form factor

### ISSUE THREAD

**Issue by patrik111** [markmal/freeship-plus-in-lazarus#45]
Hi,

Many thanks for the work being put into this!

I have found an issue with the default values in the Wave tab in the Michlet file generator.

The Y1 Value must be greater than the Y0 value for Michlet to work. 
N
ot being a programmer, I think this is what is done in the 
FreeMichletOutputDlg.pas, and the first mention I find would be line 242

Also in the exported file, there is one entry missing, a number introduced in the later versions of Michlet. After the entry 
"# Skin Friction Method (0=None, 1=ITTC1957, 2=Grigson)"
2

The entry:
"# Viscous Form Factor Method (0=None, 3=Dual)"
3 
 is needed in the output file.
Not being a programmer, I think this is what is done in the 
FreeMichletOutputDlg.pas, and the entry would be around line 1042

![MichletWaveDialogue](https://user-images.githubusercontent.com/32139980/60658490-945b5b00-9e53-11e9-975f-120eb727a0e0.JPG)

Sorry for the possibly a bit unstructured explanation.

Kind regards

**Comment by markmal** [comment]
fixed. will release soon.
