### ISSUE TITLE
Latest install for Linux?

### ISSUE THREAD

**Issue by tvld** [markmal/freeship-plus-in-lazarus#47]
What would the best way to install latest Linux / Ubuntu version? The .deb is no longer here?

( Visiting back after a long time.. Nice to see you still use the icons I once contributed. They seem a bit out-of-date now, don't they? )

**Comment by markmal** [comment]
Hi, I've released the latest version for Linux, deb and zip.

Icons are great! may be we will need more for new functions - anchoring points, permanent adjustment to a line, etc.
Your help will be greatly appreciated!

**Comment by tvld** [comment]
Super Mark, thank you. 

If you can give me a list of the icons you need, I can have a look one of these days.

**Comment by markmal** [comment]
These features are still experimental. May be later.

**Comment by tvld** [comment]
ok,Let me know ;-)
