### ISSUE TITLE
No icons at windows 7

### ISSUE THREAD

**Issue by dmitry-pozhidaev** [markmal/freeship-plus-in-lazarus#49]
I run FreeShip (FreeShip-exe.zip) on windows 7 and have no icons on toolbox panel of freeship.

I create folder for russian.ini file too. May be create simple install package for windows?
I use mac os and run Freeship at Parallels virtual mashine. So may be someone build FreeShip for native run at mac os ? 

![Снимок экрана 2019-11-18 в 12 15 14](https://user-images.githubusercontent.com/3218145/69039747-92a6c400-09fd-11ea-9ce6-fba2bd3334a4.png)

**Comment by markmal** [comment]
Please follow install-HOWTO.txt

**Comment by dmitry-pozhidaev** [comment]
Спасибище, заработало

Thank you very much!
