### ISSUE TITLE
Build Freeship for Mac OS

### ISSUE THREAD

**Issue by dmitry-pozhidaev** [markmal/freeship-plus-in-lazarus#50]
Поехали!
I will try build FreeShip for Mac OS
I instal pascal, lazarus and..
Me got linking error:

ld: library not found for -lmagic
An error occurred while linking 
FreeShip.dpr(311,0) Error: Error while linking`

I have no MAC OS development experience.
Need help!
How setup in Lazarus IDE environment variable for LD_LIBRARY_PATH?
Libmagic was installed over brew before and located at /usr/local/lib as symlink on real library.

**Comment by markmal** [comment]
You can set LD_LIBRARY_PATH in your profile.

**Comment by dmitry-pozhidaev** [comment]
So i think header was found at compile time.
It is error of linking
I set up environment var as
`echo export LD_LIBRARY_PATH="/usr/local/lib"' >> ~/.bash_profile`
And have no success still.

**Comment by markmal** [comment]
Did you try to configure project in Lazarus? 
menu Project -> Project options -> Compiler Options - > Paths -> Libraties (-Fl):

**Comment by dmitry-pozhidaev** [comment]
I write /usr/local/lib and not linking still

```
ld: library not found for -lmagic
An error occurred while linking
```

**Comment by dmitry-pozhidaev** [comment]
Марк, мне сложно изъясняться на английском и это будет криво. С твоего позволения я буду на русском писать и после завершения эпопеи со сборкой для заинтересованных можно будет кратко создать отчет о проделанной работе уже на английском.
Удалось собрать проект под маком. Спасибо форуму Лазаруса - https://forum.lazarus.freepascal.org/index.php?action=post;topic=47522.0;last_msg=340411

При запуске отображается заставка. 
Открывается главное окно и диалог с первичными данными.
При нажатии на кнопку ОК генерируется исключение - картинку со скриншотом диалогового окна 
![Снимок экрана 2019-11-24 в 20 57 06](https://user-images.githubusercontent.com/3218145/69498848-5d1e4100-0efd-11ea-9d54-4f4c3e3a6f56.png)
прилагаю.

Опыта в программировании под как под Лазарусом, так и под маком я не имею - я линуксовод кутишник, поэтому очень уповаю на твою помощь в доводке до рабочего состояния Фришипа под Мак.

**Comment by markmal** [comment]
Hi Dmitry, 
have you fixed bitmap format issue. If so, please describe, I will add the change into trunk.
