### ISSUE TITLE
Bad whorse WRML import

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#64]
With every version is getting worse VRML importing,
Here a mess file importing with FreeShip that i use some time to convert geometry to Nurbs. here what happened in this latest version..
![Istantanea_2020-04-21_11-12-53](https://user-images.githubusercontent.com/11751383/79848562-87e3c700-83c1-11ea-8d80-febb2c176fe8.png)
and below the old FreeShip.
![Istantanea_2020-04-21_11-13-31](https://user-images.githubusercontent.com/11751383/79848622-9b8f2d80-83c1-11ea-912a-809f93797724.png)
Below the file of the geometry.
[TestOBJ-wrl.zip](https://github.com/markmal/freeship-plus-in-lazarus/files/4508970/TestOBJ-wrl.zip)

**Comment by markmal** [comment]
I'll take a look.

**Comment by markmal** [comment]
is car VRML both sided or one side?

**Comment by pafurijaz** [comment]
The model i full without mirroring. because if you make half you have a creased edges in the middle and that avoid the pinch in the middle because is hard to get a tangent with other side.

**Comment by markmal** [comment]
point tolerance was hardcoded to 1e-5. Some points that close enough were merged and this caused mess in faces.
I've made tolerance autodetected from precision of coords in VRML file.
Will be in next release.

**Comment by pafurijaz** [comment]
wow the same problem due to same bug?

**Comment by pafurijaz** [comment]
Now With latest version works very well,thanks :)
