### ISSUE TITLE
merging of very small objects

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#65]
Here the example of that, below the files. a simple cube, in the original file there are 14 cubes but FreeShip recognize only 11 and merge the others.
![Istantanea_2020-04-21_11-49-14](https://user-images.githubusercontent.com/11751383/79851920-41449b80-83c6-11ea-8dab-b84588cc7201.png)

[Cubes.zip](https://github.com/markmal/freeship-plus-in-lazarus/files/4509127/Cubes.zip)
[Cube_test.ftm.zip](https://github.com/markmal/freeship-plus-in-lazarus/files/4509133/Cube_test.ftm.zip)

**Comment by markmal** [comment]
same story point tolerance was hardcoded to 1e-5. Some points that close enough were merged and this caused mess in faces.
I've made default tolerance 1e-6 and fixed sqrdistance comparison.
Now it is 14 cubes.
Will be in next release.

**Comment by pafurijaz** [comment]
Great :)

**Comment by pafurijaz** [comment]
Seem working with latest version ;) thanks!
