### ISSUE TITLE
Shade Under water

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#68]
The hull shade under water not show the color selected but a bit darker main hull color, work only with windows lines plan.
Below some images
![DWL_2020-06-02_10-44-58](https://user-images.githubusercontent.com/11751383/83500197-becbf300-a4be-11ea-9fd8-9471cea05dd7.png)
![DWL_2020-06-02_10-44-22](https://user-images.githubusercontent.com/11751383/83500202-bf648980-a4be-11ea-97d8-fc9e455129e4.png)

**Comment by markmal** [comment]
Underwater coloring is changed to translucent mode to be more natural. So underwater color now is blend of layer color and underwarer color.

**Comment by pafurijaz** [comment]
OK thanks, for response, but very low contrast and is hard to see but anyway is good knowing was not a bug. :)

**Comment by markmal** [comment]
I'll check if I can make something to improve contrast.

**Comment by pafurijaz** [comment]
very nice, even for who has visual problem..
