### ISSUE TITLE
Hiding layers doesn't work

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#74]
Hi I'm testing some times when I can with new hulls but hiding layers don't work properly, after a layer is hided the in wireframe mode the hided layer is still visible.

**Comment by markmal** [comment]
All is correct. Now there is separate checkbox "Control Net Visible". You can turn on/off control net and mesh visibility independently. Also if you need to control just visibility of layers you can use menu Layers -> Layers Visibility dialog. It is smaller and non-modal (you can keep it open while working).

**Comment by pafurijaz** [comment]
OK thanks
