### ISSUE TITLE
Panning view

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#75]
An other wrong behavior is the pan when some edges is selected, and is impossible to zoom in a specific area to select others edges to be creased, the view restart from zoom extend.

Look in the video attached
[Pan_zoom.mp4.zip](https://github.com/markmal/freeship-plus-in-lazarus/files/4777152/Pan_zoom.mp4.zip)

**Comment by markmal** [comment]
fixed

**Comment by pafurijaz** [comment]
Thanks..
