### ISSUE TITLE
Export to freecad

### ISSUE THREAD

**Issue by froussel** [markmal/freeship-plus-in-lazarus#79]
I have a dream....
Export the hull but with a configurable thickness so that you can then integrate the equipment inside: hull reinforcements, daggerboard wells, servo supports, etc...
I would like to be able to print my hulls in 3d but after having reworked them in freecad.
[https://www.facebook.com/groups/823401911152313](url)
I tried to get help on the French freecad forum
But it seems that I have tired my interlocutor
[https://forum.freecadweb.org/viewtopic.php?f=12&t=46942](url)

**Comment by markmal** [comment]
Closed as old
