### ISSUE TITLE
AppImage release request

### ISSUE THREAD

**Issue by Pinaki82** [markmal/freeship-plus-in-lazarus#84]
Please release an AppImage package of this amazing software if possible.
Thanks in advance!

**Comment by pafurijaz** [comment]
That is a request already asked but now the developing is blocked no news and answers from developer, maybe someone in the future come back, for now seem abandoned.

**Comment by Pinaki82** [comment]
[deb2appimage](https://github.com/simoniz0r/deb2appimage) can be used in the meantime until the developers provide a native AppImage binary. Thanks!
