### ISSUE TITLE
Developable plates not available after grouping surfaces on Linux X86-64

### ISSUE THREAD

**Issue by joebitgypsy** [markmal/freeship-plus-in-lazarus#87]
I have tried to develop plates from several designs, but the option is not available even after grouping faces. I have also placed groups into separate layers, as well as separating crease lines. Nothing gives me the option to create develop plates for cutting.
Running Version 5.0.36.574 X86-64 on Ubuntu 20.04.

**Comment by FIFTYSIXFACTORY** [comment]
Hi,
Perhaps you forgot to check "developable" for each needed layer, in "layer properties" window
