### ISSUE TITLE
Issues with export\import *.Part

### ISSUE THREAD

**Issue by mplekhan** [markmal/freeship-plus-in-lazarus#93]
Hello. I am having issues while export\import *.Part.
During Export  commande    the  "*.Part" file is created and is visible via file system.
When trying to Import this file into existing or new file the  Freeship_app does not shows\finds and *.Part files in folder where the *Part files are kept. I would very much appreciate help

**Comment by markmal** [comment]
Hi, the export default directory is Export, the import is Import. Please find the part for reimport in Export folder.

**Comment by markmal** [comment]
the issue with case sensitivity for filter was fixed.
