### ISSUE TITLE
propol.exe

### ISSUE THREAD

**Issue by mutissimo** [markmal/freeship-plus-in-lazarus#95]
Hi
When running "Calculation of Open Water Characteristics of B Series Propeller" the application gives an error:
"Unsupported 16-bit application"

**Comment by markmal** [comment]
Hi, what is your OS? If Win10, please enable 16-Bit Application Support.

**Comment by mutissimo** [comment]
I am using windows 10x64. The system does not allow running 16-bit applications. The application does not install on Windows 10x32.
