### ISSUE TITLE
version 5

### ISSUE THREAD

**Issue by froussel** [markmal/freeship-plus-in-lazarus#97]
Hi,

When freeship opening a file .fbm 👍 
Program exception! 
Stacktrace:

Exception class: EConvertError
Message: "" is an invalid integer
  $0000000100077605
  $00000001005BDF2E  COMPAREVERSIONS,  line 167 of Forms/FreeUpdateDlg.pas
  $00000001005BE74E  GETGITHUBRELEASES,  line 307 of Forms/FreeUpdateDlg.pas
  $00000001005BDD97  FORMCREATE,  line 152 of Forms/FreeUpdateDlg.pas
  $0000000100050113  DOCREATE,  line 939 of include/customform.inc
  $000000010004DF5A  AFTERCONSTRUCTION,  line 149 of include/customform.inc
  $0000000100055D1F  CREATE,  line 3184 of include/customform.inc
  $000000010009257E  FORMACTIVATE,  line 1068 of Forms/Main.pas
  $000000010004F846  ACTIVATE,  line 680 of include/customform.inc
  $000000010004FE05  CMACTIVATE,  line 842 of include/customform.inc
  $000000010000FED1
  $000000010003AF0F  WNDPROC,  line 2241 of include/control.inc
  $000000010002E665  WNDPROC,  line 5411 of include/wincontrol.inc
  $00000001000516D1  WNDPROC,  line 1477 of include/customform.inc
  $0000000100039878  PERFORM,  line 1581 of include/control.inc
  $00000001000586FB  SETFOCUSEDFORM,  line 899 of include/screen.inc
  $0000000100054457  SETFOCUSEDCONTROL,  line 2556 of include/customform.inc
  $00000001005BDF2E  COMPAREVERSIONS,  line 167 of Forms/FreeUpdateDlg.pas
  $00000001005BE74E  GETGITHUBRELEASES,  line 307 of Forms/FreeUpdateDlg.pas
  $00000001005BDD97  FORMCREATE,  line 152 of Forms/FreeUpdateDlg.pas
  $0000000100050113  DOCREATE,  line 939 of include/customform.inc
  $000000010004DF5A  AFTERCONSTRUCTION,  line 149 of include/customform.inc
  $0000000100055D1F  CREATE,  line 3184 of include/customform.inc
  $000000010009257E  FORMACTIVATE,  line 1068 of Forms/Main.pas
  $000000010004F846  ACTIVATE,  line 680 of include/customform.inc
  $000000010004FE05  CMACTIVATE,  line 842 of include/customform.inc
  $000000010000FED1
  $000000010003AF0F  WNDPROC,  line 2241 of include/control.inc
  $000000010002E665  WNDPROC,  line 5411 of include/wincontrol.inc
  $00000001000516D1  WNDPROC,  line 1477 of include/customform.inc
  $0000000100039878  PERFORM,  line 1581 of include/control.inc
  $00000001000586FB  SETFOCUSEDFORM,  line 899 of include/screen.inc
  $0000000100054457  SETFOCUSEDCONTROL,  line 2556 of include/customform.inc

**Comment by markmal** [comment]
fixed
