### ISSUE TITLE
Can't compile on Debian 11 or 12

### ISSUE THREAD

**Issue by lanigb** [markmal/freeship-plus-in-lazarus#98]
Hi,
I would like to propose some improvements to Freeship but for the moment, I can't compile it. I had the same error on Debian 11 or 12.
`FileIconGtk.pas(11,3) Fatal: Impossible de trouver LazGio2 utilisé par FileIconGtk. Activer le drapeau "Utiliser l'unité" de l'unité LazGio2 dans le paquet LCL.`
" Can't find LazGio2 used by FileIconGtk. Activate flag "Use unit" of LazGio2 unit in LCL package".
Where in Lazarus can I find this flag ?
Thanks,

**Comment by markmal** [comment]
Please reach to Lazarus support
