### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by gskillas** [markmal/freeship-plus-in-lazarus#99]
I am using openSUSE Leap 15.4, with lazarus 2.2.6 Revision: Unknown, Free Pascal Compiler version 3.2.2 [2023/06/28] for x86_64 Qt version 5.15.2, Inkscape 1.2.2 (b0a8486541, 2022-12-01).

In the Makefile modified the inkscape parameters:
`build-icons:
        for i in $(ICON_SIZES); do inkscape --export-type="png" --export-filename=freeship-$$i.png -w $$i -h $$i FreeShip_icon.svg ; done
        convert freeship-32.png freeship.xpm`
then did:
`> make distclean
> make `
which stops with a compilation error:
`~/freeship-plus-in-lazarus/./Forms/FreeFilePreviewDialog.pas(2462,1)  (3049) procedure/function LocationEditorPanelClick(TObject);
FreeFilePreviewDialog.pas(2469) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile Project, Mode: Gtk2 Debug, Target: FreeShip: stopped with exit code 1
Error: (lazbuild) failed compiling of project ~/freeship-plus-in-lazarus/FreeShip.lpi
make: *** [Makefile:21: build] Error 2`

Note that this is the very last procedure in the file.
What is going wrong? I do not see any immediate reason as to why it compiles `procedure TFreeFilePreviewDialog.ShellPathPanelOnClick(Sender: TObject);` but not `procedure TFreeFilePreviewDialog.LocationEditorPanelClick(Sender: TObject);`

I can test whatever you need to get to the bottom of this.

Best regards and thank you for your effort,

George

**Comment by markmal** [comment]
Please do not build with Qt. This project uses GTK3.
